/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.sinhVien;
import Model.sinhVienTableModel;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Scanner;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormQuanLySinhVien extends javax.swing.JFrame {

    Scanner nhap = new Scanner(System.in);
    public JLabel lbThongBaoTuoi;
    public DefaultTableModel model;
    
    public FormQuanLySinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTenDangNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMatKhau = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfHoTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTuoi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbGioiTinh = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangSinhVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/logoKMA2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, 40));

        tfTenDangNhap.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        tfTenDangNhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(tfTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 46, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 90, 40));

        tfMatKhau.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        tfMatKhau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(tfMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 46, 160, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel9.setText("Họ tên:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 70, 40));

        tfHoTen.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        tfHoTen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(tfHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 116, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel8.setText("Tuổi:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 60, 40));

        tfTuoi.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        tfTuoi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tfTuoi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(tfTuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 116, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel6.setText("Giới tính:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 40));

        cbGioiTinh.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        jPanel1.add(cbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 150, 40));

        btnThem.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnThem.setText("Thêm");
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnSua.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnSua.setText("Sửa");
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnXoa.setText("Xóa");
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        btnReset.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnReset.setText("Clear");
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnQuayLai.setText("Đăng xuất");
        jPanel1.add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Danh Sách Sinh Viên");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/4dcc12351effc7a19eee.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        bangSinhVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bangSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bangSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                 TÊN ĐĂNG NHẬP", "                     MẬT KHẨU", "                      HỌ TÊN", "                          TUỔI ", "                     GIỚI TÍNH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bangSinhVien.setRowHeight(30);
        jScrollPane1.setViewportView(bangSinhVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setTableModel(sinhVienTableModel tableModel) {
        bangSinhVien.setModel(tableModel);
    }
    
    public void addThemActionListener(ActionListener log) {
        btnThem.addActionListener(log);
    }

    public void addSuaActionListener(ActionListener log) {
        btnSua.addActionListener(log);
    }

    public void addXoaActionListener(ActionListener log) {
        btnXoa.addActionListener(log);
    }

    public void addResetActionListener(ActionListener log) {
        btnReset.addActionListener(log);
    }
    public void addQuayLaiActionListener(ActionListener log){
        btnQuayLai.addActionListener(log);
    }
    public void addClickTable (MouseListener log){
        bangSinhVien.addMouseListener(log);
        
    }
    
    public boolean checkRong(){
        if(tfTenDangNhap.getText().equals("") ||tfMatKhau.getText().equals("")||tfHoTen.getText().equals("")||tfTuoi.getText().equals("") ){
            return true ;
        }
        return false ;
    
            }
    
    // --------------------------------------------------------------------lấy dữ liệu từ các text field đổi thành 1 đôi tượng sinh vien 
    public sinhVien getSinhVien() {

        String tenDangNhap = tfTenDangNhap.getText();
        String mk = tfMatKhau.getText();
        String ht = tfHoTen.getText();
        String gt = cbGioiTinh.getSelectedItem().toString();
        sinhVien sv = null ;
         int tuoi = 0 ;
        try {
            tuoi = Integer.parseInt(tfTuoi.getText());
         sv = new sinhVien(tenDangNhap, mk, ht, tuoi, gt);
        } catch (Exception e) {
            showMessage("Tuổi không hợp lệ xin vui lòng nhập lại",1);
        }
        return sv;
    }
    /////-------------------------------------------------------hàm check họ tên không được có ký tự lạ nào 
    public boolean checkHoTen(String text){
        return true ;
    }
    /////////////---------------------------------------------------hàm check mat khau khong duoc duoi 3 ký tụ
    public boolean checkMatKhau(String text){
        if(text.length() <= 3){
             return false ;
        }else{
            return true ;
        }
    }
    //-----------------------------------------------hàm check tuoi khong qua cao qua thap 
    public boolean checkTuoi(int tuoi){
      if(tuoi < 18 || tuoi > 100){
           return true ;
      }
      else{
           return false ;
      }

    }
    ////////////////////////----------------------------------------------------------------------------------------- show các thông báo 
    public void showMessage(String msg, int option) {
        switch (option) {
            case 1: {
                JOptionPane.showMessageDialog(null, msg);
                break;
            }
            case 2: {
                int result = JOptionPane.showConfirmDialog(null, null, msg, JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {}
                break ;
            }  
        }
    }
    //--------------------------------------------------------------- hàm reset các text File
    public void reset(){
        tfTenDangNhap.setText("");
        tfMatKhau.setText("");
        tfHoTen.setText("");
        tfTuoi.setText("");
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLySinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable bangSinhVien;
    public javax.swing.JButton btnQuayLai;
    public javax.swing.JButton btnReset;
    public javax.swing.JButton btnSua;
    public javax.swing.JButton btnThem;
    public javax.swing.JButton btnXoa;
    public javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField tfHoTen;
    public javax.swing.JTextField tfMatKhau;
    public javax.swing.JTextField tfTenDangNhap;
    public javax.swing.JTextField tfTuoi;
    // End of variables declaration//GEN-END:variables
}
