/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author VietNguyen
 */
public class adminForm extends javax.swing.JFrame {
    private StudentManagementPanel mStudentPanel;
    private BookManagementPanel mBookPanel;
    private AuthorPanel mAuthorPanel;
    /**
     * Creates new form mainForm
     */
    
    public adminForm() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_logout = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_usercontrol = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        bth_bookcontrol = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        bth_help = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        tabMainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuFile_exit = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        menuStudentManagement = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_bookManagement = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jToolBar1.setRollover(true);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/logout-icon-32.png"))); // NOI18N
        btn_logout.setText("Đăng Xuất ");
        btn_logout.setFocusable(false);
        btn_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_logout);
        jToolBar1.add(jSeparator4);

        btn_usercontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        btn_usercontrol.setText("Quản Lý Bạn Đọc");
        btn_usercontrol.setFocusable(false);
        btn_usercontrol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_usercontrol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_usercontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usercontrolActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_usercontrol);
        jToolBar1.add(jSeparator5);

        bth_bookcontrol.setIcon(new javax.swing.ImageIcon("E:\\Code\\Java\\New folder\\QuanLySinhVien-main\\QuanLySinhVien\\Image\\books-icon.png")); // NOI18N
        bth_bookcontrol.setText("Quản Lý Sách");
        bth_bookcontrol.setFocusable(false);
        bth_bookcontrol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bth_bookcontrol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bth_bookcontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bth_bookcontrolActionPerformed(evt);
            }
        });
        jToolBar1.add(bth_bookcontrol);
        jToolBar1.add(jSeparator6);

        bth_help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/Actions-help-about-icon-32.png"))); // NOI18N
        bth_help.setText("Tác Giả");
        bth_help.setFocusable(false);
        bth_help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bth_help.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bth_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bth_helpActionPerformed(evt);
            }
        });
        jToolBar1.add(bth_help);
        jToolBar1.add(jSeparator7);

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\Code\\Java\\New folder\\QuanLySinhVien-main\\QuanLySinhVien\\Image\\Actions-application-exit-icon.png")); // NOI18N
        jButton1.setText("Thoát");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jMenu1.setText("Hệ Thống");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/logout-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Đăng Xuất");
        jMenu1.add(jMenuItem1);

        menuFile_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/Button-Close-icon-16.png"))); // NOI18N
        menuFile_exit.setText("Thoát");
        menuFile_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFile_exitActionPerformed(evt);
            }
        });
        jMenu1.add(menuFile_exit);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        menuStudentManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        menuStudentManagement.setText("Quản Lý Bạn Đọc");
        menuStudentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStudentManagementActionPerformed(evt);
            }
        });
        jMenu2.add(menuStudentManagement);
        jMenu2.add(jSeparator2);

        menu_bookManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        menu_bookManagement.setText("Quản Lý Sách");
        menu_bookManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_bookManagementActionPerformed(evt);
            }
        });
        jMenu2.add(menu_bookManagement);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ Giúp");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/Help-icon-16.png"))); // NOI18N
        jMenuItem5.setText("Nội Dung");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/icon/Actions-help-about-icon-16.png"))); // NOI18N
        jMenuItem6.setText("Giới Thiệu");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);
        jMenu3.add(jSeparator3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(tabMainBoard, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuFile_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFile_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuFile_exitActionPerformed

    private void menuStudentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStudentManagementActionPerformed
        if(mStudentPanel == null){
            mStudentPanel = new StudentManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/hinhnen/icon/10207-man-student-light-skin-tone-icon-16.png"));
            tabMainBoard.addTab("Quản Lý Bạn Đọc", icon, mStudentPanel, "Quản Lý Sinh Viên");
        }
        tabMainBoard.setSelectedComponent(mStudentPanel);
    }//GEN-LAST:event_menuStudentManagementActionPerformed

    private void menu_bookManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_bookManagementActionPerformed
        if (mBookPanel == null){
            mBookPanel = new BookManagementPanel();
            ImageIcon icon = new  ImageIcon(getClass().getResource("/hinhnen/icon/Actions-document-edit-icon-16.png"));
            tabMainBoard.addTab("Quản Lý Sách", icon, mBookPanel, "Quản Lý Sách");
        }
        tabMainBoard.setSelectedComponent(mBookPanel);
    }//GEN-LAST:event_menu_bookManagementActionPerformed

    private void btn_usercontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usercontrolActionPerformed
        if(mStudentPanel == null){
            mStudentPanel = new StudentManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/hinhnen/icon/10207-man-student-light-skin-tone-icon-16.png"));
            tabMainBoard.addTab("Quản Lý Bạn Đọc ", icon, mStudentPanel, "Quản Lý Sinh Viên");
        }
        tabMainBoard.setSelectedComponent(mStudentPanel);
    }//GEN-LAST:event_btn_usercontrolActionPerformed

    private void bth_bookcontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bth_bookcontrolActionPerformed
        if (mBookPanel == null){
            mBookPanel = new BookManagementPanel();
            ImageIcon icon = new  ImageIcon(getClass().getResource("/hinhnen/icon/Actions-document-edit-icon-16.png"));
            tabMainBoard.addTab("Quản Lý Sách ", icon, mBookPanel, "Quản Lý Sách");
        }
        tabMainBoard.setSelectedComponent(mBookPanel);
    }//GEN-LAST:event_bth_bookcontrolActionPerformed

    private void bth_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bth_helpActionPerformed
        if (mAuthorPanel == null){
            mAuthorPanel = new AuthorPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/hinhNen/icon/Actions-help-about-icon-16.png"));
            tabMainBoard.addTab("Thông Tin ", icon, mAuthorPanel, "Tác Giả");
        }
        tabMainBoard.setSelectedComponent(mAuthorPanel);
    }//GEN-LAST:event_bth_helpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new adminForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bth_bookcontrol;
    private javax.swing.JButton bth_help;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_usercontrol;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuFile_exit;
    private javax.swing.JMenuItem menuStudentManagement;
    private javax.swing.JMenuItem menu_bookManagement;
    private javax.swing.JTabbedPane tabMainBoard;
    // End of variables declaration//GEN-END:variables
}
